services:
  # Сервис ингредиентов
  ingredient-service:
    build: ./ingredient-service
    ports:
      - "8001:80"
    environment:
      - DB_HOST=ingredient-db
    depends_on:
      - ingredient-db
    networks:
      - recipes-network

  # База данных для ингредиентов
  ingredient-db:
    image: postgres:13
    environment:
      POSTGRES_DB: ingredient_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./postgres-data/ingredient:/var/lib/postgresql/data
    networks:
      - recipes-network

  # Сервис рецептов
  recipe-service:
    build: ./recipe-service
    ports:
      - "8002:80"
    environment:
      - DB_HOST=recipe-db
      - INGREDIENT_SERVICE_URL=http://ingredient-service:8001
    depends_on:
      - recipe-db
      - ingredient-service
    networks:
      - recipes-network

  # База данных для рецептов
  recipe-db:
    image: postgres:13
    environment:
      POSTGRES_DB: recipe_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./postgres-data/recipe:/var/lib/postgresql/data
    networks:
      - recipes-network

networks:
  recipes-network:
    driver: bridge