services:
  # Ваши существующие сервисы
  recipe-service:
    build: ./recipe-service
    ports: ["8001:80"]
    depends_on:
      recipe-db:
        condition: service_healthy

  ingredient-service:
    build: ./ingredient-service
    ports: ["8002:80"]
    depends_on:
      ingredient-db:
        condition: service_healthy
    environment:
      DB_HOST: ingredient-db
      DB_DATABASE: ingredients
      DB_USERNAME: root
      DB_PASSWORD: secret

<<<<<<< HEAD
  # Новый User Service
=======
  
>>>>>>> origin/main
  user-service:
    build: ./user-service
    ports: ["8003:80"]
    depends_on:
      user-db:
        condition: service_healthy
    environment:
<<<<<<< HEAD
      DB_HOST: user-db  # Важно: используем имя сервиса
=======
      DB_HOST: user-db
>>>>>>> origin/main
      DB_DATABASE: users_db
      DB_USERNAME: root
      DB_PASSWORD: secret

<<<<<<< HEAD
  # Базы данных
=======

>>>>>>> origin/main
  recipe-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: recipes
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]

  ingredient-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ingredients
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]

<<<<<<< HEAD
  # Новая БД для User Service
=======

>>>>>>> origin/main
  user-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: users_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]